//**********************************************
//
//  @author Max Hubenthal
//
//  Problem Two -- projecteuler.net
//    Each new term in the Fibonacci sequence is 
//    generated by adding the previous two terms.
//    By starting with 1 and 2, the first 10 terms will 
//    be:
//      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//    By considering the terms in the Fibonacci 
//    sequence whose values do not exceed four million,
//    find the sum of the even-valued terms.
//
//  This solution is a simple brute force algorithm. 
//  The Fibonacci sequence can be generated recursively,
//  but that would have been much more expensive regarding
//  resources.
//
//**********************************************

public class EulerTwo{
  public static void main (String[] args){
    int numA = 0;
    int numB = 1;
    int numC = 2;
    int sum = 0;
    
    while (numC < 4000000){
      if ((numC % 2)==0){
        sum += numC;
        numA = numB;
        numB = numC;
        numC = numA + numB;
      }
      else{
        numA = numB;
        numB = numC;
        numC = numA + numB;
      }
    }
    System.out.println(sum);
  }
}